[build]
builder = "NIXPACKS"
watchPatterns = ["server/**"]

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
configFile = "server/package.json"